### ISSUE TITLE
[question] How to set DO_NOT_AUTO_START?

### ISSUE THREAD

**Issue by Freed-Wu** [stefano-m/lua-dbus_proxy#13]
Comes from https://github.com/ibus/ibus/issues/2669

TIA!

**Comment by stefano-m** [comment]
You can pass the `flags` parameter when creating a proxy object. See https://stefano-m.github.io/lua-dbus_proxy/#Proxy:new

Probably something like:

``` lua
local lgi = require("lgi")

p = require 'dbus_proxy'
proxy = p.Proxy:new(
  {
    bus = p.Bus.SESSION,
    name = "org.freedesktop.IBus",
    interface = "org.freedesktop.IBus",
    path = "/org/freedesktop/IBus",
    flags = lgi.Gio.DBusProxyFlags.DO_NOT_AUTO_START
  }
)

```

**Comment by Freed-Wu** [comment]
How to assign bus address? I try

```lua
proxy0 = p.Proxy:new(
  {
    bus = p.Bus["unix:path=/home/wzy/.cache/ibus/dbus-c2RX3vlC,guid=d8c2b7e5b01276d5bcc582f666ae1289"],
    name = "org.freedesktop.IBus",
    interface = "org.freedesktop.IBus",
    path = "/org/freedesktop/IBus",
    flags = lgi.Gio.DBusProxyFlags.DO_NOT_AUTO_START
  }
)
```

It will give me

```
(process:979743): GLib-GIO-CRITICAL **: 12:38:38.335: g_dbus_connection_signal_subscribe: assertion 'sender == NULL || (g_dbus_is_name (sender) && (connection->flags & G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION))' failed

(process:979743): GLib-GIO-CRITICAL **: 12:38:38.335: g_dbus_connection_signal_subscribe: assertion 'sender == NULL || (g_dbus_is_name (sender) && (connection->flags & G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION))' failed

Timeout was reached

Stack trace:
        #0 [C]: in function ?
        #1 [C]: in function 'error'
        #2 /home/wzy/.local/share/lua/5.1/dbus_proxy/_proxy.lua:584: in function 'new'
```

**Comment by Freed-Wu** [comment]
I doubt it is because https://github.com/stefano-m/lua-dbus_proxy/blob/master/src/dbus_proxy/_bus.lua#L34 pass None to Connection Flags. https://github.com/ibus/ibus/issues/2669#issuecomment-2308008274

**Comment by Freed-Wu** [comment]
Change Gio.DBusConnectionFlags.NONE to Gio.DBusConnectionFlags.AUTHENTICATION_CLIENT + Gio.DBusConnectionFlags.MESSAGE_BUS_CONNECTION can solve problem.

**Comment by stefano-m** [comment]
Hi!

Your original question was about how to add flags to a proxy object, which I showed you how to do.

I understand from your latest messages that in addition to that, you need to be able to set flags on a Bus object.

It would be best if we discussed separate topics on separate issues rather than renaming old ones.

Please create a new issue explaining with as much detail as possible:

1. what you are trying to achieve
1. what problem you are having
2. where you think the problem may be
3. how you think the problem can be solved
4. what solution you suggest
5. what tests you ran and what results you got

This will help keeping issues clean and separate.

Thanks!

**Comment by stefano-m** [comment]
@Freed-Wu see if version 0.10.4 helps your use case.

I added a new function called `Bus.new` that can be use to specify connection flags.

- https://github.com/stefano-m/lua-dbus_proxy/releases/tag/v0.10.4
- https://luarocks.org/modules/stefano-m/dbus_proxy/0.10.4-1
